package KieRule;
import com.example.droolsexample.model.Pet;

dialect "mvel"

rule "Dog"
when
petObject : Pet("Dog"==type || "dog"==type);
then
petObject.setUrl("https://source.unsplash.com/1600x900/?dog");
end;

rule "Cat"
when
petObject : Pet("Cat"==type || "cat"==type);
then
petObject.setUrl("https://source.unsplash.com/1600x900/?cat");
end;

rule "Cow"
when
petObject : Pet("Cow"==type || "cow"==type);
then
petObject.setUrl("https://source.unsplash.com/1600x900/?cow");
end;

rule "Llama"
when
petObject : Pet("Llama"==type && "llama"==type);
then
petObject.setUrl("https://source.unsplash.com/1600x900/?llama");
end;
